= BUGS

== OpenFlow Protocol

=== Out of Scope

* This program verifies the structural representation of OpenFlow messages. It does not verify that values within that structure are semantically valid.

=== Missing Support

* Version 1.0
** OFPMP_EXPERIMENTER smaller than 8 bytes (no exp_type)
** OFPT_QUEUE_GET_CONFIG_REQUEST ?

* Version 1.1
** OFPMP_TABLE multipart reply message
** OFPMP_GROUP multipart reply message
** OFPMP_QUEUE multipart reply message

* Version 1.2
** OFPMP_TABLE multipart reply message

=== Limits

* This program handles backward compatibility with earlier OpenFlow versions by converting them to the latest "wire" format. All OpenFlow versions have a 65535 byte limit on message size. Certain 1.0, 1.1, 1.2 messages exceed this 65535 byte limit when converted to the 1.3 or later versions. (It may be necessary to relax the internal 65535 byte limit for multipart messages in the future.)

** OFPT_FEATURES_REPLY
** OFPT_PACKET_OUT
** OFPT_FLOW_MOD
** OFPT_QUEUE_GET_CONFIG_REPLY

== Security

* There are no sandbox mechanisms in place yet (e.g. seccomp-bpf)

* TLS verification just checks the authenticity of the peer certificate chain against the provided *verifier* certificate. This assumes that the *verifier* certificate is a private authority. There is *no* checking of the subject name, host names, or addresses in the peer certificate (see Identity::tls_verify_callback in the source code).

* DTLS cookies are not supported.

== Miscellaneous

* There is currently no DNS support for host endpoints. All connections must use IP addresses.

* Prerequisite checking for Experimenter OXM's is not supported.

== Packet Capture and TCP Reassembly

* If the first segment of a new flow is not a SYN packet, the sequence number at the
beginning of the data specifies the intitial sequence number. Earlier segments that
arrive out of order are ignored. 

* If an unfinished flow is logically restarted with a SYN TCP packet, any unconsumed data from a partial OpenFlow message is discarded.

* IP fragments are not supported.


