= LIBOFP: OpenFlow to YAML Converter image:https://travis-ci.org/byllyfish/libofp.svg?branch=develop["Build Status", link="https://travis-ci.org/byllyfish/libofp"]
:icons: font
:toc:
ifdef::env-github[]
:toc-placement: preamble
endif::[]

== What is Libofp?

The *libofp* program translates binary https://www.opennetworking.org/sdn-resources/openflow[OpenFlow] messages to http://www.yaml.org/spec/1.2/spec.html[YAML] and back again. It provides a simple, uniform object syntax for working with the OpenFlow protocol programmatically.

* Support Linux and OS X
* Supports OpenFlow versions 1.0, 1.1, 1.2, 1.3, 1.4
* Supports YAML 1.2 and JSON
* Optional JSON RPC Microservice supports:
** multiple incoming or outgoing connections
** auxiliary connections
** TLS and DTLS

Libofp is a *tool* in the unix tradition. You can use `netcat` in a pipe to feed OpenFlow messages to a switch or controller:

[source,console]
----
$ libofp encode input.yml | nc -w 3 10.0.0.1 6653 | libofp decode
----

You can parse a .pcap file with `tcpflow` and then decode all the OpenFlow 
messages, while retaining metadata such as timestamps:

[source,bash]
----
#!/bin/bash
tcpflow -I -r saved.pcap -o "/tmp/flow_$$" 
libofp decode --use-findx "/tmp/flow_$$/*.findx"
----

Libofp includes a JSON-RPC microservice that can operate as an OpenFlow 
controller, agent, or both simultaneously. The JSON-RPC microservice can control
the OpenFlow protocol over an IPC channel using asynchronous JSON events.

[source,console]
----
$ libofp jsonrpc
----

=== YAML to OpenFlow

The following YAML input will produce an OpenFlow 1.3 message:

[source,yaml]
----
type: PACKET_OUT
version: 4  // <1>
msg:
  buffer_id: NO_BUFFER
  in_port: CONTROLLER  // <2>
  actions: 
    - action: OUTPUT
      port: 0x11  // <3>
      max_len: MAX
  data: 'ffffffffffff0000000000010800'
----
<1> For version, we use the `wire version`; 4 refers to the 1.3 spec.
<2> Use strings for special values and flags.
<3> YAML supports hexadecimal numbers.

The YAML syntax is based on OpenFlow 1.4, but the same input
can generate earlier protocol version messages. Libofp is intelligent about
translating between OpenFlows versions. For example,
here's a FlowMod message specified using OpenFlow 1.4 syntax, but which will 
output a "1.0" message because version 1 is explicitly specified.

[source,yaml]
----
  type: FLOW_MOD
  version: 1  // <1>
  msg:
    cookie: 0
    cookie_mask: 0xFFFFFFFFFFFFFFFF   // <2>
    table_id: 0  // <2>
    command: ADD
    idle_timeout: 10
    hard_timeout: 30
    priority: 2
    buffer_id: NO_BUFFER
    out_port: ANY
    out_group: ANY
    flags: [ SEND_FLOW_REM, CHECK_OVERLAP ] // <3>
    match:
      - field: IN_PORT
        value: 1
      - field: IPV4_SRC   // <4>
        value: '192.168.1.1'
    instructions:
      - instruction: APPLY_ACTIONS
        actions:
          - action: OUTPUT
            port: 2
            max_len: MAX
----
<1> Here, we're specifying the 1.0 OpenFlow specification.
<2> These values are `lost` because they are not supported in OpenFlow 1.0.
<3> Flags are specified using arrays of strings.
<4> Match field dependencies are automatically added when necessary.

NOTE: There is some trickiness under the hood to let one object syntax support multiple OpenFlow versions. Later versions of OpenFlow _recycle_ some enumerated values used in version 1.0 for different purposes. Libofp automatically translates these constants between versions and maps 1.4-based actions back to their corresponding 1.0-defined actions.

=== OpenFlow to YAML

Given a binary OpenFlow message, `libofp` can translate it back to a human-readable
YAML (or JSON) object. Here's the binary for an OpenFlow OFPT_ERROR message in hexadecimal:

[source,hex]
----
01010013 00000062 00010001 FFFF1234 567890
----

Decoding this binary OpenFlow message yields:

[source,yaml]
----
type:            ERROR
xid:             0x00000062
version:         0x01
msg:             
  type:            OFPET_BAD_REQUEST
  code:            OFPBRC_BAD_TYPE
  data:            FFFF1234567890
----

== Installation

Before you build, you need a C++11 compiler, cmake and git.

On Ubuntu, use apt-get to install the dependencies.
[source,console]
----
$ sudo apt-get -yq update
$ sudo apt-get install build-essential cmake git
----

On Mac OS X, you can obtain cmake from http://cmake.org/download/.

To build the software:

[source,console]
----
$ git clone --recursive https://github.com/byllyfish/libofp.git
$ mkdir libofp/Build
$ cd libofp/Build
$ cmake ..
$ make
$ make test
$ make install
----

== Examples

To translate a text file into binary OpenFlow messages:

[source,console]
----
$ libofp encode -o output.bin input.yml
----

To translate a text file into binary OpenFlow messages, while ignoring
sets of match fields with missing prerequisites:

[source,console]
----
$ libofp encode --unchecked-match -o output.bin input.yml
----

To translate a text file of compact, single line JSON objects separated by
linefeeds:

[source,console]
----
$ libofp encode --json input.json
----

To decode a file of binary OpenFlow messages to YAML:

[source,console]
----
$ libofp decode input.bin
----

To decode a file of binary OpenFlow messages to compact single-line JSON objects:

[source,console]
----
$ libofp decode --json "filename"
----

To decode binary OpenFlow messages to a valid JSON array of objects:

[source,console]
----
$ libofp decode --json-array "filename"
----

To decode binary OpenFlow messages with the additional check that the resulting
YAML produces the same binary message when re-encoded:

[source,console]
----
$ libofp decode --verify-output "filename"
----

The `libofp help` tool provides information about the schema used for reading/writing 
OpenFlow messages in YAML. To obtain information about the syntax for the 
'FLOW_MOD' message:

[source,console]
----
$ libofp help flow_mod
----

To list all supported OXM fields:

[source,console]
----
$ libofp help --fields
----

== License

This software is licensed under the terms of the *MIT License*.


